{
    'name': 'Aset Bangunan',
    'version': '12.0.1.0.0',
    'description': 'Master Data Bangunan',
    'summary': 'Modul Data Bangunan',
    'author': 'Siroja Muniro',
    'website': 'http://rojaweb.000webhostapp.com',
    'license': 'LGPL-3',
    'category': 'Extra Tools',
    'depends': ['mail'],
    'data': [
        'security/ir.model.access.csv',
        'data/data.xml',
        'views/views1.xml',
        'views/views2.xml',
        'views/views3.xml',
        'views/views4.xml',
        'views/views5.xml',
    ],
    'demo': [],
    'auto_install': False,
    'application': True,
    'installable': True,
}